AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true

################################################################################
# METRICS
################################################################################
Metrics/LineLength:
  Max: 120
################################################################################
# LAYOUT
################################################################################
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/DotPosition:
  EnforcedStyle: trailing

################################################################################
# STYLES
################################################################################
# The `do this and return` pattern is too useful to discard, but we don't want
# to deal with them in conditionals, where order-of-operations matters. So we
# restrict to that.
# see http://www.prestonlee.com/2010/08/04/ruby-on-the-perl-origins-of-and-versus-and-and-or/
Style/AndOr:
  EnforcedStyle: conditionals

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

# DoubleNegation is a useful pattern
Style/DoubleNegation:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false
