AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
Metrics/LineLength:
  Enabled: false
Style/DotPosition:
  EnforcedStyle: trailing
Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
