#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.95
yabai -m config window_shadow                on
yabai -m config window_border                off
yabai -m config window_border_width          4
yabai -m config active_window_border_color   0xffaa5759
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                   0
yabai -m config bottom_padding                0
yabai -m config left_padding                  0
yabai -m config right_padding                 0
yabai -m config window_gap                    5


# Rules for apps
yabai -m rule --add label="Floating 1password" app="1Password" manage=off
yabai -m rule --add label="Floating ColorSlurp" app="ColorSlurp"  manage=off
yabai -m rule --add label="Floating Dash" app="Dash" manage=off
yabai -m rule --add label="Floating Fantastical" app="Fantastical Helper" manage=off
yabai -m rule --add label="Floating GNUplot" app="gnuplot_qt" manage=off
yabai -m rule --add label="Floating Harvest" app="Harvest" manage=off
yabai -m rule --add label="Floating Join Vivaldi" app="Vivaldi" title="Join - Vivaldi" manage=off
yabai -m rule --add label="Floating PCalc" app="PCalc" manage=off
yabai -m rule --add label="Floating Scrcpy" app="scrcpy" manage=off
yabai -m rule --add label="Floating SysPrefs" app="System Preferences" manage=off
yabai -m rule --add label="Floating stickies" app="Stickies" manage=off

echo "yabai configuration loaded.."
