#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.95
yabai -m config window_shadow                on
yabai -m config window_border                off
yabai -m config window_border_width          8
yabai -m config active_window_border_color   0xffaa5759
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                   0
yabai -m config bottom_padding                0
yabai -m config left_padding                  0
yabai -m config right_padding                 0
yabai -m config window_gap                    5


# Rules for apps
# System prefs should always float
yabai -m rule --add label="Floating SysPrefs" app="System Preferences" manage=off
# Floating dash windows
yabai -m rule --add label="Floating Dash" app="Dash" manage=off
# Fantastical floats
yabai -m rule --add label="Floating Fantastical" app="Fantastical Helper" manage=off
# Scrcpy floats
yabai -m rule --add label="Floating Scrcpy" app="scrcpy" manage=off
# Gnuplot floats
yabai -m rule --add label="Floating GNUplot" app="gnuplot_qt" manage=off


echo "yabai configuration loaded.."
