gui:
  expandFocusedSidePanel: true
  showRandomTip: false
  showFileTree: false
  branchColors:
    'jeffs': 'cyan'
confirmOnQuit: true
quitOnTopLevelReturn: true
keybinding:
  universal:
    quit: Q
    quitWithoutChangingDirectory: <c-q>
    return-alt1: q # tig style q
