[preview]
revision_command = ["show", "--color", "always", "-r", "$change_id", "--tool", ":color-words"]
file_command = ["diff", "--color", "always", "-r", "$change_id", "$file", "--tool", ":color-words"]
show_at_start = true
[ui.colors]
"selected" = { bg = "#373B41" }
"revisions details selected" = { bg = "#373B41" }

[custom_commands]
"tug" = { key = ["t"], args = ["bookmark", "move", "--from", "closest_bookmark($change_id)", "--to", "closest_pushable($change_id)"] }
"ksdiff" = { key = ["k"], args = ["diff", "--tool", "ksdiff", "-r", "$change_id"], show="interactive" }
