#!/usr/bin/env sh

# Mode definitions
:: default : hs -c "hs.alert('Default')"; yabai -m config window_border off
:: switcher @ : hs -c "hs.alert('Switcher')"; yabai -m config window_border on
:: swap @ : hs -c "hs.alert('Swap')"; yabai -m config window_border on
:: layout @ : hs -c "hs.alert('Layout')"; yabai -m config window_border on

# Mode escape hatch
switcher, swap, layout < escape ; default

# Switcher mode
hyper - f ; switcher

switcher < a ; swap
switcher < s ; layout
swap < f ; switcher

# Switcher move focus
switcher < h : yabai -m window --focus west
switcher < j : yabai -m window --focus south
switcher < k : yabai -m window --focus north
switcher < l : yabai -m window --focus east

switcher < n :  yabai -m display --focus prev
switcher < m : yabai -m display --focus next

# Layout Mode
layout < a : yabai -m space --layout bsp; hs -c "hs.alert('BSP')"
layout < s : yabai -m space --layout float; hs -c "hs.alert('Float')"

layout < r : yabai -m space --rotate 90

layout < x : yabai -m space --mirror x-axis
layout < c : yabai -m space --mirror y-axis

layout < b : yabai -m space --balance

# Window specific layout commands
layout < p : yabai -m window --toggle sticky;\
             yabai -m window --toggle topmost;\
             yabai -m window --toggle border;\
             yabai -m window --toggle pip

layout < z : yabai -m window --toggle zoom-fullscreen
layout < f : yabai -m window --toggle float

layout < h : yabai -m window --resize left:20:0
layout < j : yabai -m window --resize bottom:0:20
layout < k : yabai -m window --resize top:0:20
layout < l : yabai -m window --resize right:20:0

layout < shift - h : yabai -m window --resize left:-20:0
layout < shift - j : yabai -m window --resize bottom:0:-20
layout < shift - k : yabai -m window --resize top:0:-20
layout < shift - l : yabai -m window --resize right:-20:0


# Swap commands
swap < h : yabai -m window --swap west
swap < j : yabai -m window --swap south
swap < k : yabai -m window --swap north
swap < l : yabai -m window --swap east

swap < n :  yabai -m window --display prev; yabai -m display --focus prev
swap < m : yabai -m window --display next; yabai -m display --focus next
swap < 1 :  yabai -m window --display 1; yabai -m display --focus 1
swap < 2 : yabai -m window --display 2; yabai -m display --focus 2
swap < 2 : yabai -m window --display 2; yabai -m display --focus 2
swap < 4 : yabai -m window --display 4; yabai -m display --focus 4
