"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

# Username, gpg key, and other per-machine settings are in ./conf.d/local.toml

[signing]
behavior = "own"
backend = "gpg"

[revsets]
log = 'present(@) | ancestors(immutable_heads().., 5) | present(trunk())'

[ui]
default-command = "log"
diff-formatter = "difft"
diff-editor = ":builtin"

[aliases]
e = ["edit"]
p = ["git", "push"]
n = ["new"]
bu = ["bookmark", "move", "--from", "closest_main(@-)", "--to", "@-"]
foo = ['bar', 'baz']
d = ["describe"]
s = ["show"]
a = ["abandon"]
tug = ["bookmark", "move", "--from", "closest_bookmark(@-)", "--to", "@-"]

[revset-aliases]
'local_trunk()' = '''
latest(
  bookmarks(exact:"main") |
  bookmarks(exact:"master") |
  bookmarks(exact:"trunk") |
  root()
)
'''
'closest_bookmark(to)' = 'heads(::to & bookmarks())'
'closest_main(to)' = "heads(::to & (bookmarks(exact:'main')|bookmarks(exact:'master')))"

[templates]
git_push_bookmark = '"jeffs/push/" ++ change_id.short()'
commit_trailers = """
if(!trailers.contains_key("JJ-Change-Id"), "JJ-Change-Id: " ++ self.change_id())
"""

[template-aliases]
"format_timestamp(timestamp)" = """
if(timestamp.before("1 week ago"),
timestamp,
timestamp.ago()
)
"""

[core]
fsmonitor = "watchman"

[core.watchman]
register-snapshot-trigger = true

[merge-tools.ksdiff]
diff-invocation-mode = "file-by-file"
diff-args = ["--partial-changeset", "$left", "$right"]
merge-args = ["--merge", "--output", "$output", "--base", "$base", "$left", "$right"]
