[tools]
rust = "latest"
node = "latest"
elixir = "latest"
erlang = "latest"
deno = "latest"
"cargo:cargo-binstall" = "1.10.8"
"cargo:cargo-generate" = "0.23.3"
"cargo:lucky_commit" = "2.2.5"
"cargo:sd" = "1.0.0"
"cargo:spurdify" = "0.1.1"

[settings]
jobs = 8
asdf_compat = true
experimental = true
