[tools]
rust = "stable"
node = "latest"
elixir = "latest"
erlang = "latest"
deno = "latest"
"cargo:cargo-binstall" = "1.14.1"
"cargo:cargo-generate" = "0.23.3"
"cargo:lucky_commit" = "2.2.5"
"cargo:sd" = "1.0.0"
"cargo:spurdify" = "0.1.1"
bun = "latest"

[settings]
jobs = 8
experimental = true
