[tools]
"cargo:cargo-generate" = "0.23.4"
"cargo:lucky_commit" = "2.2.5"
"cargo:sd" = "1.0.0"
"cargo:spurdify" = "0.1.1"
bun = "latest"
cargo-binstall = "latest"
cosign = "latest"
deno = "latest"
elixir = "latest"
erlang = "latest"
hk = "1.2.2"
rust = "stable"
slsa-verifier = "latest"
usage = "2.2.2"
pkl = "latest"
watchexec = "latest"
"npm:jj-stack" = "latest"

[settings]
jobs = 8
experimental = true

[settings.npm]
bun = true
